### ISSUE TITLE
Why the value of "should_deploy" is true?

### ISSUE THREAD

**Issue by fbzhong** [trufflesuite/truffle-deployer#4]
Hi,

I am wondering why the value of "should_deploy" in deploy.js is true. That cause the contract will be deployed in every test phase, which introduce me lot trouble to deal with that.

As my understanding, the "truffle deploy/migrate" command is used to deploy the contract, and save the addresses for testing phase. As the "should_deploy" var introduced, it breaks old behavior.

I'd like to have a further discussion with you.

**Comment by kandrianov** [comment]
Basically, it's not a bug, it's a feature) So, for every test group you will have clean deployment.

**Comment by cgewecke** [comment]
Closing this for housekeeping - there's a similar issue open over at Truffle main repo [here]().  Perhaps  we should make this feature configurable since @fbzhong is one of several people who don't wish to see this behavior. 

A workaround is to have logic in the migrations that inspects the network object and skips migrations if the context is testing.
